### ISSUE TITLE
Django wants to add a new migration in django 3.2

### ISSUE THREAD

**Issue by tomvanderlee** [matthiask/django-cabinet#13]
Django want to add a migration to alter the id field on folder and file to `BigAutoField` in 3.2. Other apps will depend on a migration that is locally added on the cabinet app, but nobody has (except for me locally),

**Comment by matthiask** [comment]
Ah yes, thanks. We should probably specify the auto field type in `apps.py`.

Do you want to test this out and submit a pull request if it does?

**Comment by tomvanderlee** [comment]
Yes, will do.

**Comment by tomvanderlee** [comment]
I've created a PR

**Comment by matthiask** [comment]
Great, thanks!
