### ISSUE TITLE
Update to latest release at GitHub

### ISSUE THREAD

**Issue by DmytroLitvinov** [matthiask/django-cabinet#8]

**Comment by matthiask** [comment]
I'm sorry but I don't understand this issue. Could you try explaining the problem and what might be done about it? Thanks!

**Comment by DmytroLitvinov** [comment]
Could you please mark the latest release `0.11` at https://github.com/matthiask/django-cabinet/releases as "latest" release :)
Right now it is `0.3` version marked as latest :)

**Comment by matthiask** [comment]
Ah wow, I don't remember ever creating those releases by hand. I have deleted the GitHub releases now.

The [CHANGELOG](https://github.com/matthiask/django-cabinet/blob/master/CHANGELOG.rst) is the place which should always contain up-to-date release informations for django-cabinet.

Thanks for the report!
